# Generated by Django 5.0.2 on 2024-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=40)),
                ('data', models.DateTimeField(max_length=40)),
                ('open_value', models.IntegerField(max_length=40)),
                ('close_value', models.IntegerField(max_length=40)),
            ],
        ),
    ]
