# Generated by Django 5.0.2 on 2024-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='close_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='open_value',
            field=models.IntegerField(),
        ),
    ]
