# Generated by Django 5.0.2 on 2024-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_marketdata_close_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='data',
            field=models.CharField(max_length=40),
        ),
    ]
